### PR TITLE
Update based on voxpupuli/modulesync_config 0.14.1. This might fix #246, #248 and #253

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by dhoppe** [comment]
@3flex @alexjfisher I did a modulesync and merged your changes from #246 and #248 into this PR, but it looks like php::extension also needs a rewrite.

**Comment by alexjfisher** [comment]
@dhoppe Were you able to test the refactoring changes I made didn't break anything?

**Comment by dhoppe** [comment]
@alexjfisher I only checked against TravisCI and did not have time to test via virtual machine. :(

**Comment by jyaworski** [comment]
@dhoppe please rebase.

**Comment by dhoppe** [comment]
@jyaworski Done

**Comment by jyaworski** [comment]
@dhoppe please rebase... again? :(

**Comment by dhoppe** [comment]
@jyaworski I did a rebase and updated against modulesync_config 0.15.0. Please do a quick merge, before master changes again. ;)

**Pull request merged**
