### PR TITLE
fixtures: don't pin puppetlabs-apt version

### PR DESCRIPTION
**Pull request by 3flex**
Previously this was frozen to 1.8.x, released about 18 months ago.

### CODE REVIEW

**Comment by alexjfisher** [comment]
Not sure about this. I think most other modules get fixtures from git.
eg
https://github.com/voxpupuli/puppet-archive/blob/master/.fixtures.yml
https://github.com/voxpupuli/puppet-corosync/blob/master/.fixtures.yml
https://github.com/voxpupuli/puppet-jira/blob/master/.fixtures.yml
https://github.com/voxpupuli/puppet-mcollective/blob/master/.fixtures.yml
https://github.com/voxpupuli/puppet-collectd/blob/master/.fixtures.yml

Those are the first 5 I picked at semi-random (they were in my history)

**Comment by alexjfisher** [comment]
@3flex I think you're right about the `apt` module though.

The metadata has the following.
```
{ "name": "puppetlabs/apt", "version_requirement": ">= 1.8.0 < 3.0.0" }
```

**Comment by alexjfisher** [comment]
@3flex Would you like to rename the PR before we merge?

**Comment by 3flex** [comment]
Done!

**Pull request merged**
