### PR TITLE
Add support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by grant-veepshosting**
#### Pull Request (PR) description
Add support for Ubuntu 22.04

#### This Pull Request (PR) fixes the following issues
Add support for Ubuntu 22.04

### CODE REVIEW

**Comment by smortex** [comment]
This is likely not working:
https://github.com/voxpupuli/puppet-php/blob/master/manifests/globals.pp#L32-L36

I suggest:
1. wait for the 22.04 version to become available;
2. adjust [voxpupuli/puppet_metadata](https://github.com/voxpupuli/puppet_metadata) and release a new version that is aware of this new release;
3. have CI working for this work and fix it.

**Comment by msu-ts** [comment]
Hello, as mentioned above, Ubuntu 22.04 is now available. Is there an update here?

That helps temporarily:
``` 
--- manifests/globals_old.pp    2022-06-24 14:03:42.558691014 +0200
+++ manifests/globals.pp        2022-06-24 13:56:42.580355330 +0200
@@ -32,6 +32,7 @@
     'Ubuntu' => $facts['os']['release']['major'] ? {
       '18.04' => '7.2',
       '20.04' => '7.4',
+      '22.04' => '8.1',
       default => fail("Unsupported Ubuntu release: ${fact('os.release.major')}"),
     },
     default => '5.x',
``` 

Thanks in advance.

**Comment by kenyon** [comment]
Let's retry the CI.

**Comment by smortex** [comment]
@grant-veepshosting can you please rebase your changes to fix conflicts (and the CI failure should vanish at the same time) and add this release to metadata.json so that we can see which tests need work (I updated my first message above now that Puppet packages are available for 22.04)?

**Comment by kenyon** [comment]
Ubuntu 22.04 support done in #672.

**Pull request closed without merging**
