### PR TITLE
Feature/pm ondemand

### PR DESCRIPTION
**Pull request by derkgort**
Hi,

This adds the option to use the ondemand pm.

### CODE REVIEW

**Comment by derkgort** [comment]
These fails are not in my added code...

**Comment by yastupin** [comment]
Looks like you're adding the `pm_process_idle_timeout` option here.
Is this the expected commit?

**Comment by derkgort** [comment]
Yes.
quoting the php-fpm documentation:

> pm.process_idle_timeout mixed
The number of seconds after which an idle process will be killed. Used only when pm is set to ondemand. Available units: s(econds)(default), m(inutes), h(ours), or d(ays). Default value: 10s.

**Comment by yastupin** [comment]
Ok thanks for the explanation!

**Pull request merged**
