### PR TITLE
Prefix package resources with the provider to avoid collision between pecl/pear and OS packages

### PR DESCRIPTION
**Pull request by jonhattan**
Fix for #320

### CODE REVIEW

**Comment by Vincent--** [comment]
I believe

```
        name         => $real_name,
        ensure       => $ensure,
```
should be in the opposite order (ensure should always be first, see: http://puppet-lint.com/checks/ensure_first_param/ )

```
        ensure       => $ensure,
        name         => $real_name,
```

Regards,
Vincent

**Comment by jonhattan** [comment]
Rebased and fixed params order

**Comment by bastelfreak** [comment]
@jonhattan there are still failing travis jobs. We recently added acceptance tests. Can you please rebase and take a look at the failing tests?

**Comment by bastelfreak** [comment]
Thanks for opening this issue. It hasn't seen activity in a while, so I'm going to close the issue. This doesn't mean that we don't think this issue is valid, we're just trying to assess what issues are still relevant. If you still need this(even if you're not willing to work on it yourself) please feel free to reopen it. Again thanks for opening the issue, users who report bugs and ask for features are some of the most important players in the open source community. Feel free to hop by #voxpupuli on irc.freenode.net if you'd like to chat with us about any of this.

**Comment by jonhattan** [comment]
@bastelfreak Only project managers can reopen PRs/issues.

This PR is still relevant.

**Comment by bastelfreak** [comment]
I'm not sure why, but I can't reopen it :thinking: 
If you still want to get this merged please provide a new PR and rebase against our current master.

**Pull request closed without merging**
