### PR TITLE
Arch Linux: Fix package names and set correct php-fpm user (root -> http)

### PR DESCRIPTION
**Pull request by jkroepke**

### CODE REVIEW

**Comment by jkroepke** [comment]
From logs, I can't see any error here. I need help here OR consider to remove Archlinux

**Comment by bastelfreak** [comment]
Very odd, the php-fpm service is working fine after the restart :thinking: 
2022-07-03-094547_1715x760_scrot

**Comment by bastelfreak** [comment]
it's trying to rerestart php-fpm with `service`, which is wrong:
```
  Debug: /Stage[main]/Php/Php::Extension[gd]/Php::Extension::Config[gd]/Php::Config[gd]/Php::Config::Setting[/etc/php/conf.d/gd.ini: extension]/Ini_setting[/etc/php/conf.d/gd.ini: extension]: The container Php::Config::Setting[/etc/php/conf.d/gd.ini: extension] will propagate my refresh event
  Debug: Php::Config::Setting[/etc/php/conf.d/gd.ini: extension]: The container Php::Config[gd] will propagate my refresh event
  Debug: Php::Config[gd]: The container Php::Extension::Config[gd] will propagate my refresh event
  Debug: Php::Extension::Config[gd]: The container Php::Extension[gd] will propagate my refresh event
  Debug: Php::Extension[gd]: The container Class[Php] will propagate my refresh event
  Info: Php::Extension[gd]: Scheduling refresh of Service[php-fpm]
  Debug: Executing: '/usr/bin/systemctl is-active -- php-fpm'
  Debug: Executing: '/usr/bin/systemctl is-enabled -- php-fpm'
  Debug: Executing: '/usr/bin/systemctl is-active -- php-fpm'
  Debug: Executing: '/usr/bin/systemctl show --property=NeedDaemonReload -- php-fpm'
  Debug: Executing: 'service php-fpm reload'
  Debug: Running journalctl command to get logs for systemd restart failure: journalctl -n 50 --since '5 minutes ago' -u php-fpm --no-pager
  Debug: Executing: 'journalctl -n 50 --since '5 minutes ago' -u php-fpm --no-pager'
  Error: /Service[php-fpm]: Failed to call refresh: Systemd restart for php-fpm failed!
  journalctl log for php-fpm:
  Jul 03 07:51:11 archlinuxrolling-64-1 systemd[1]: Starting The PHP FastCGI Process Manager...
  Jul 03 07:51:11 archlinuxrolling-64-1 php-fpm[5105]: [NOTICE] fpm is running, pid 5105
  Jul 03 07:51:11 archlinuxrolling-64-1 php-fpm[5105]: [NOTICE] ready to handle connections
  Jul 03 07:51:11 archlinuxrolling-64-1 systemd[1]: Started The PHP FastCGI Process Manager.
  Jul 03 07:51:11 archlinuxrolling-64-1 php-fpm[5105]: [NOTICE] systemd monitor interval set to 10000ms
  Error: /Service[php-fpm]: Systemd restart for php-fpm failed!
  journalctl log for php-fpm:
```

**Comment by jkroepke** [comment]
If extensions are installed here, why is restarting wrong?

**Comment by bastelfreak** [comment]
@jkroepke I pushed the systemd change in another PR. could you rebase your `allow-unsupported` against my `fpm` branch, and then rebase your `fix-arch` branch against your `allow-unsupported`? That will give us three seperate PRs where #663 has a clean CI.

**Comment by jkroepke** [comment]
Thanks god, the gh cli supports pr checkouts from upstream repositories flawless...

**Comment by jkroepke** [comment]
Mention: I also disable pear on Arch, since it's not available no main repositories (missing in the title)

**Pull request merged**
