### PR TITLE
Compatibility with Softwarecollections (SCL)

### PR DESCRIPTION
**Pull request by diLLec**
While using this module with RHEL/CentOS and SCL-PHP (https://www.softwarecollections.org/en), I came across some problems (mainly path and name specifics). Please review my changes and merge them to master.

Greetings,
Michael

### CODE REVIEW

**Comment by diLLec** [comment]
ok, I'll look into it

**Comment by diLLec** [comment]
Hi @vinzent,

the tests are fine now. The changes do not introduce any breaking changes since the additional parameters are optional. Please verify and merge :)

Greetings,
diLLec

**Comment by vinzent** [comment]
@diLLec could you rebase your commits to get a clean commit history?

- including the title and text of the Github PR in the first commit 
- squashing all other commits to the first

howto: `git fetch upstream && git rebase -i upstream/master`, replace first pick with reword and all other pick with fixup. This should leave you with one commit for all - check with  `git log`. and then `git push --force`

**Comment by diLLec** [comment]
@vinzent thanks for the howto - commit is nice and clean now

**Comment by jsha09** [comment]
Hi ... Any chance this change will get merged in soon?

**Comment by bastelfreak** [comment]
@jsha09 I would love to, but we've a long list of conflicts here. This feature branch needs to be rebased. Feel free to do this and submit it as a new PR. We're happy to review and merge it.

----

@diLLec are you still interested in this PR? Can you please rebase it?

**Comment by bastelfreak** [comment]
Thanks for rebasing. Can you take a look at the used email address in the commit? It isn't associated with your github account.

**Comment by diLLec** [comment]
Hi,

the code is rebased now and tests are passing (only the debian install seams to be broken - issue that is not related to the changes of this PR).

Greetings,
Michael

**Comment by oranenj** [comment]
I fixed the conflicts and did another PR, and @bastelfreak merged it, so this can be closed

Thanks to @diLLec for the work!

**Pull request closed without merging**
