### PR TITLE
Add Ubuntu 22.04 support

### PR DESCRIPTION
**Pull request by martialblog**
#### Pull Request (PR) description
Since the PR #658  to add support for Ubuntu 22.04 wasn't moving forward, I tried to get things moving.

This adds Ubuntu 22.04 support.

#### This Pull Request (PR) fixes the following issues

No open issue regarding this feature.

### CODE REVIEW

**Comment by martialblog** [comment]
There were some existing lint errors, I added a new commit to address them.

**Comment by martialblog** [comment]
There are currently no Ubuntu 22.04 Acceptance Tests in the CI.

Ran the beaker suite locally without any issues:

```
BEAKER_setfile=ubuntu2204-64 bundle exec rake beaker
...
Finished in 1 minute 31.16 seconds (files took 36.78 seconds to load)
8 examples, 0 failures
```

**Comment by smortex** [comment]
Please update `metadata.json` to add Ubuntu 22.04. That way the CI will run on his OS too.

**Comment by martialblog** [comment]
@smortex Hi, thanks for the hint. I updated the metadata

**Comment by martialblog** [comment]
Anything I can help with to get this train in the station? I'd love to see this merged for a downstream project. 

Cheers
Markus

**Review by kenyon — APPROVED** [review]

**Pull request merged**
