### PR TITLE
Confine pecl provider to where pear command is available

### PR DESCRIPTION
**Pull request by walkamongus**

### CODE REVIEW

**Comment by walkamongus** [comment]
Fixes #340

**Comment by bastelfreak** [comment]
Thanks for the PR @walkamongus!

**Comment by ktreese** [comment]
When will this be released to the forge?  It appears the current forge version was pushed 20 days prior to this merge, which I need to fix some issues it's causing in our production environment.

**Comment by bastelfreak** [comment]
Hi @ktreese, I am doing a new release in https://github.com/voxpupuli/puppet-php/pull/394

**Pull request merged**
