### PR TITLE
Support other versions of remi repo on redhat

### PR DESCRIPTION
**Pull request by edestecd**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @edestecd, thanks for the PR. Can you provide acceptance tests that use different values for the parameter?

**Comment by edestecd** [comment]
@bastelfreak tests added

**Comment by edestecd** [comment]
@Dan33l I didn't see any acceptance tests for debian or ubuntu for example. SO i don't know how you usually write them. I'll try and have a look at some others.

**Comment by Dan33l** [comment]
In this module, you can find : 
 * the [helper_acceptance](https://github.com/voxpupuli/puppet-php/blob/master/spec/spec_helper_acceptance.rb). The role of the helper is to prepare system under tests (SUT) to be ready for being able to receive tests.
 * 2 spec files making tests [php56_spec.rb](https://github.com/voxpupuli/puppet-php/blob/master/spec/acceptance/php56_spec.rb) [php_spec.rb](https://github.com/voxpupuli/puppet-php/blob/master/spec/acceptance/php_spec.rb)
 * the file (.travis.yml)[https://github.com/voxpupuli/puppet-php/blob/master/.travis.yml] that permit to run tests defined by previous items. All lines with `BEAKER` are acceptance tests executed for each PR.

So tests about all supported OSes should be present. For instance [this line launch tests under CentOS7 with puppet5](https://github.com/voxpupuli/puppet-php/blob/master/.travis.yml#L73)

**Pull request merged**
