### PR TITLE
Add support for Debian 12 (bookworm)

### PR DESCRIPTION
**Pull request by jcharaoui**
#### Pull Request (PR) description

Not much is changed for PHP in this upcoming release, except for the version of PHP shipped which is now 8.2

### CODE REVIEW

**Comment by jcharaoui** [comment]
Debian 12 `bookworm` has been released over 3 months ago.

**Comment by smortex** [comment]
This is currently blocked by the absence of Debian 12 packages for Puppet.

When packages are available, CI will be able to run the test suite on Debian 12, and we will be able to merge this. Thanks

**Comment by jcharaoui** [comment]
> This is currently blocked by the absence of Debian 12 packages for Puppet.

Puppet packages are indeed available for Debian 12: https://packages.debian.org/bookworm/puppet-agent

**Comment by smortex** [comment]
I am speaking about the *AIO Puppet Agent* package form Puppetlabs/Perforce.

**Comment by BuJo** [comment]
Just here to confirm that the branch works very well on Debian 12.

**Comment by ftrojahn** [comment]
In https://github.com/voxpupuli/puppet-php/blob/master/manifests/repo/debian.pp#L53
shouldn't there be another `,'12'` added in this line, too?
At least this was needed to add the sury repo in bookworm successfully.

**Comment by kenyon** [comment]
@ftrojahn yes, plus an update to the tests that came in https://github.com/voxpupuli/puppet-php/commit/a9ca0335cef275ad37dd70c6cb7899be73693abc. Or better, just remove those version checks so that we don't have to keep updating them.

**Comment by jcharaoui** [comment]
I updated the specs, relevant tests now green!

**Review by kenyon — APPROVED** [review]

**Comment by joec4i** [comment]
Hi @kenyon Can we cut a release to include this? 🙏

**Pull request merged**
